;;; ghostel-module-test.el --- Tests for ghostel: module -*- lexical-binding: t; -*-

;;; Commentary:

;; Native module download, install, sidecar versioning, platform tag.

;;; Code:

(require 'ghostel-test-helpers)

(ert-deftest ghostel-test-module-download-url-uses-requested-version ()
  "Requested download versions are decoupled from the package version."
  (let ((ghostel-github-release-url "https://example.invalid/releases"))
    (cl-letf (((symbol-function 'ghostel--module-asset-name)
               (lambda () "ghostel-module-x86_64-linux.so")))
      (should (equal "https://example.invalid/releases/download/v0.7.1/ghostel-module-x86_64-linux.so"
                     (ghostel--module-download-url "0.7.1"))))))

(ert-deftest ghostel-test-module-download-url-uses-latest-release ()
  "A nil download version uses the latest release asset."
  (let ((ghostel-github-release-url "https://example.invalid/releases"))
    (cl-letf (((symbol-function 'ghostel--module-asset-name)
               (lambda () "ghostel-module-x86_64-linux.so")))
      (should (equal "https://example.invalid/releases/latest/download/ghostel-module-x86_64-linux.so"
                     (ghostel--module-download-url nil))))))

(ert-deftest ghostel-test-download-module-defaults-to-minimum-version ()
  "Automatic downloads pin to the minimum supported native module version."
  (let* ((ghostel--minimum-module-version "0.7.1")
         (captured-version :unset)
         (download-dest nil)
         (published nil)
         (dir (make-temp-file "ghostel-dl-" t)))
    (unwind-protect
        (cl-letf (((symbol-function 'ghostel--module-download-url)
                   (lambda (&optional version)
                     (setq captured-version version)
                     "https://example.invalid/releases/download/v0.7.1/ghostel-module-x86_64-linux.so"))
                   ((symbol-function 'ghostel--download-file)
                    (lambda (_url dest)
                      (setq download-dest dest)
                      t))
                   ((symbol-function 'ghostel--publish-downloaded-module-archive)
                    (lambda (archive publish-dir)
                      (setq published (list archive publish-dir))
                      t))
                   ((symbol-function 'delete-file)
                    (lambda (&rest _) nil))
                   ((symbol-function 'message)
                    (lambda (&rest _))))
          (should (ghostel--download-module dir))
          (should (equal "0.7.1" captured-version))
          (should (equal (list (downcase download-dest)
                               (downcase (file-name-as-directory
                                          (expand-file-name dir))))
                         (mapcar #'downcase published)))
          (should (equal (downcase (expand-file-name
                                    "ghostel-module-x86_64-linux.so"
                                    dir))
                         (downcase download-dest))))
      (when (file-exists-p dir)
        (delete-directory dir t)))))

(ert-deftest ghostel-test-download-module-prefix-uses-requested-version ()
  "Prefix downloads pass the requested release version through unchanged."
  (let ((ghostel--minimum-module-version "0.7.1")
        (captured-version :unset)
        (captured-latest nil))
    (let ((native-comp-enable-subr-trampolines nil))
      (cl-letf (((symbol-function 'locate-library)
                 (lambda (_) "C:/ghostel/ghostel.el"))
                ((symbol-function 'file-exists-p)
                 (lambda (&rest _) nil))
                ((symbol-function 'ghostel--read-module-download-version)
                 (lambda () "0.8.0"))
                ((symbol-function 'ghostel--download-module)
                 (lambda (_dir &optional version latest-release)
                   (setq captured-version version
                         captured-latest latest-release)
                   ;; Bail before `module-load' — its mock can't be
                   ;; intercepted from native-compiled callers in Emacs 31.
                   (throw 'ghostel-test-bail nil)))
                ((symbol-function 'message)
                 (lambda (&rest _))))
        (catch 'ghostel-test-bail
          (ghostel-download-module '(4)))
        (should (equal "0.8.0" captured-version))
        (should-not captured-latest)))))

(ert-deftest ghostel-test-download-module-prefix-empty-uses-latest ()
  "Prefix download treats blank input as a request for the latest release."
  (let ((captured-version :unset)
        (captured-latest nil))
    (let ((native-comp-enable-subr-trampolines nil))
      (cl-letf (((symbol-function 'locate-library)
                 (lambda (_) "C:/ghostel/ghostel.el"))
                ((symbol-function 'file-exists-p)
                 (lambda (&rest _) nil))
                ((symbol-function 'ghostel--read-module-download-version)
                 (lambda () nil))
                ((symbol-function 'ghostel--download-module)
                 (lambda (_dir &optional version latest-release)
                   (setq captured-version version
                         captured-latest latest-release)
                   ;; Bail before `module-load' — its mock can't be
                   ;; intercepted from native-compiled callers in Emacs 31.
                   (throw 'ghostel-test-bail nil)))
                ((symbol-function 'message)
                 (lambda (&rest _))))
        (catch 'ghostel-test-bail
          (ghostel-download-module '(4)))
        (should (null captured-version))
        (should captured-latest)))))

(ert-deftest ghostel-test-download-file-is-atomic ()
  "`ghostel--download-file' writes via a temp sibling and renames into place.
The destination inode must change so any Emacs that has the previous
file mmap'd keeps a valid mapping (issue #247)."
  (let* ((dir (make-temp-file "ghostel-dl-" t))
         (dest (expand-file-name "ghostel-module.so" dir)))
    (unwind-protect
        (progn
          (with-temp-file dest (insert "old-payload"))
          (set-file-modes dest #o644)
          (let ((old-inode (file-attribute-inode-number (file-attributes dest))))
            (cl-letf (((symbol-function 'url-retrieve-synchronously)
                       (lambda (&rest _)
                         (let ((buf (generate-new-buffer " *ghostel-fake-http*")))
                           (with-current-buffer buf
                             (set-buffer-multibyte nil)
                             (insert "HTTP/1.1 200 OK\r\n\r\nnew-payload"))
                           buf))))
              (should (ghostel--download-file "https://example.invalid/x" dest)))
            (should (equal "new-payload"
                           (with-temp-buffer
                             (set-buffer-multibyte nil)
                             (insert-file-contents-literally dest)
                             (buffer-string))))
            (let ((new-inode (file-attribute-inode-number (file-attributes dest))))
              (should-not (equal old-inode new-inode)))
            ;; No stale temp files left behind on success.
            (dolist (f (directory-files dir nil "\\." t))
              (should-not (string-match-p "\\.tmp\\." f)))))
      (when (file-exists-p dir)
        (delete-directory dir t)))))

(ert-deftest ghostel-test-download-module-creates-missing-directory ()
  "`ghostel--download-module' creates DIR before writing the module.
Regression for the auto-install path: setting `ghostel-module-directory'
to a path that does not yet exist used to fail silently because the
temp-file write under that directory errored out."
  (let* ((parent (make-temp-file "ghostel-dl-parent-" t))
         (dir (expand-file-name "sub/dir/" parent))
         (asset "ghostel-module-x86_64-linux.tar.xz")
         (download-dest nil)
         (published nil))
    (unwind-protect
        (progn
          (should-not (file-exists-p dir))
           (cl-letf (((symbol-function 'ghostel--module-download-url)
                      (lambda (&optional _version)
                        (format "https://example.invalid/releases/latest/download/%s" asset)))
                     ((symbol-function 'ghostel--download-file)
                      (lambda (_url dest)
                        (setq download-dest dest)
                        (should (file-directory-p (file-name-directory dest)))
                        t))
                     ((symbol-function 'ghostel--publish-downloaded-module-archive)
                      (lambda (archive publish-dir)
                        (setq published (list archive publish-dir))
                        t))
                     ((symbol-function 'delete-file)
                      (lambda (&rest _) nil)))
             (should (ghostel--download-module dir nil t)))
           (should (file-directory-p dir))
           (should (equal (downcase (expand-file-name asset dir))
                          (downcase download-dest)))
           (should (equal (list (downcase download-dest)
                                (downcase (file-name-as-directory
                                           (expand-file-name dir))))
                          (list (downcase (car published))
                                (downcase (cadr published))))))
      (when (file-exists-p parent)
        (delete-directory parent t)))))

(ert-deftest ghostel-test-download-file-cleans-up-on-failure ()
  "A failed HTTP response leaves no stale temp file behind."
  (let* ((dir (make-temp-file "ghostel-dl-" t))
         (dest (expand-file-name "ghostel-module.so" dir)))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'url-retrieve-synchronously)
                     (lambda (&rest _)
                       (let ((buf (generate-new-buffer " *ghostel-fake-http*")))
                         (with-current-buffer buf
                           (set-buffer-multibyte nil)
                           (insert "HTTP/1.1 404 Not Found\r\n\r\nnope"))
                         buf))))
            (should-not (ghostel--download-file "https://example.invalid/x" dest)))
          (should-not (file-exists-p dest))
          (dolist (f (directory-files dir nil "\\." t))
            (should-not (string-match-p "\\.tmp\\." f))))
      (when (file-exists-p dir)
        (delete-directory dir t)))))

(ert-deftest ghostel-test-module-directory-defaults-to-resource-root ()
  "When `ghostel-module-directory' is nil, the resource root is used."
  (let ((ghostel-module-directory nil))
    (cl-letf (((symbol-function 'ghostel--resource-root)
               (lambda () "/pkg/ghostel/")))
      (should (equal (downcase (file-name-as-directory
                                (expand-file-name "/pkg/ghostel/")))
                     (downcase (ghostel--module-directory)))))))

(ert-deftest ghostel-test-module-directory-honours-custom-value ()
  "When set, `ghostel-module-directory' takes precedence."
  (let ((ghostel-module-directory "~/custom/ghostel/"))
    (cl-letf (((symbol-function 'ghostel--resource-root)
               (lambda () "/pkg/ghostel/")))
      (should (equal (downcase (file-name-as-directory
                                (expand-file-name "~/custom/ghostel/")))
                     (downcase (ghostel--module-directory)))))))

(ert-deftest ghostel-test-download-module-targets-custom-directory ()
  "Interactive download writes into `ghostel-module-directory' when set."
  (let ((ghostel-module-directory "/custom/dir/")
        (captured-dir nil))
    (let ((native-comp-enable-subr-trampolines nil))
      (cl-letf (((symbol-function 'ghostel--resource-root)
                 (lambda () "/pkg/ghostel/"))
                ((symbol-function 'file-exists-p)
                 (lambda (&rest _) nil))
                ((symbol-function 'make-directory)
                 (lambda (&rest _)))
                ((symbol-function 'ghostel--read-module-download-version)
                 (lambda () nil))
                ((symbol-function 'ghostel--download-module)
                 (lambda (dir &optional _v _l)
                   (setq captured-dir dir)
                   (throw 'ghostel-test-bail nil)))
                ((symbol-function 'message)
                 (lambda (&rest _))))
        (catch 'ghostel-test-bail
          (ghostel-download-module nil))
        (should (equal (downcase (file-name-as-directory
                                  (expand-file-name "/custom/dir/")))
                       (downcase captured-dir)))))))

(ert-deftest ghostel-test-load-module-looks-in-custom-directory ()
  "`ghostel--load-module' loads the module from `ghostel-module-directory'."
  (let* ((ghostel-module-directory "/custom/dir/")
         (loaded-path nil)
         (had-feat (featurep 'ghostel-module))
         (saved-new (and (fboundp 'ghostel--new)
                         (symbol-function 'ghostel--new))))
    (unwind-protect
        (progn
          (when had-feat
            (setq features (delq 'ghostel-module features)))
          (when saved-new
            (fmakunbound 'ghostel--new))
          (cl-letf (((symbol-function 'ghostel--resource-root)
                     (lambda () "/pkg/ghostel/"))
                    ((symbol-function 'file-exists-p)
                     (lambda (path)
                       (string-prefix-p (expand-file-name "/custom/dir/") path)))
                    ((symbol-function 'module-load)
                     (lambda (path) (setq loaded-path path)))
                    ((symbol-function 'ghostel--check-module-version)
                     (lambda (&rest _))))
            (ghostel--load-module)))
      (when saved-new
        (fset 'ghostel--new saved-new))
      (when had-feat
        (cl-pushnew 'ghostel-module features)))
    (should loaded-path)
    (should (string-prefix-p (expand-file-name "/custom/dir/")
                             loaded-path))))

(ert-deftest ghostel-test-compile-module-invokes-zig-build ()
  "Source compilation runs zig build directly."
  (let ((source-dir (ghostel-test--fixture-dir "ghostel-build"))
        (default-directory nil)
        (messages nil)
        (warnings nil)
        (process-invocation nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'message)
                 (lambda (fmt &rest args)
                   (push (apply #'format fmt args) messages)))
                ((symbol-function 'display-warning)
                 (lambda (&rest args)
                   (push args warnings)))
                ((symbol-function 'ghostel--resource-root)
                 (lambda () source-dir))
                ((symbol-function 'ghostel--publish-built-module-artifacts)
                 (lambda (&rest _) t))
                ((symbol-function 'process-file)
                 (lambda (program infile buffer display &rest args)
                   (setq process-invocation
                         (list program infile buffer display args default-directory))
                   0)))
        (should (ghostel--compile-module source-dir))
        (should (equal
                 (list "zig" nil "*ghostel-build*" nil
                       '("build" "-Doptimize=ReleaseFast" "-Dcpu=baseline") source-dir)
                 process-invocation))
        (should-not warnings)))))

(ert-deftest ghostel-test-compile-module-moves-to-dest-dir ()
  "Compilation publishes the produced runtime bundle into DEST-DIR."
  (let ((published nil)
        (warnings nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'ghostel--resource-root)
                 (lambda () "/src/ghostel/"))
                ((symbol-function 'message) (lambda (&rest _)))
                ((symbol-function 'display-warning)
                 (lambda (&rest args) (push args warnings)))
                ((symbol-function 'process-file)
                 (lambda (&rest _) 0))
                ((symbol-function 'ghostel--publish-built-module-artifacts)
                 (lambda (source-dir dest-dir)
                   (setq published (list source-dir dest-dir)))))
        (should (ghostel--compile-module "/custom/dir/"))
        (should-not warnings)
        (should (equal (list (downcase (expand-file-name "zig-out/bin" "/src/ghostel/"))
                             (downcase "/custom/dir/"))
                       (mapcar #'downcase published)))))))

(ert-deftest ghostel-test-compile-module-warns-when-build-missing ()
  "When the build returns success but no module file appears, warn."
  (let ((warnings nil))
    (let ((native-comp-enable-subr-trampolines nil))
      (cl-letf (((symbol-function 'ghostel--resource-root)
                 (lambda () "/src/ghostel/"))
                ((symbol-function 'file-exists-p)
                 (lambda (_) nil))
                ((symbol-function 'message) (lambda (&rest _)))
                ((symbol-function 'display-warning)
                 (lambda (&rest args) (push args warnings)))
                ((symbol-function 'process-file)
                 (lambda (&rest _) 0)))
        (ghostel--compile-module "/src/ghostel/")
        (should warnings)))))

(ert-deftest ghostel-test-module-compile-command-uses-zig-build ()
  "Interactive compilation uses zig build directly."
  (let ((compile-invocation nil)
        (default-directory nil)
        (ghostel-module-directory nil))
    (let ((native-comp-enable-subr-trampolines nil))
      (cl-letf (((symbol-function 'ghostel--resource-root)
                 (lambda () "C:/ghostel/"))
                ((symbol-function 'compile)
                 (lambda (command &optional comint)
                   (setq compile-invocation (list command comint default-directory))
                   (current-buffer))))
        (ghostel-module-compile)
        (should (equal "zig build -Doptimize=ReleaseFast -Dcpu=baseline"
                       (nth 0 compile-invocation)))
        (should (eq t (nth 1 compile-invocation)))
        (should (equal (downcase "C:/ghostel/")
                       (downcase (nth 2 compile-invocation))))))))

(ert-deftest ghostel-test-module-compile-installs-when-dest-differs ()
  "Interactive compile installs the built module into `ghostel-module-directory'.
A `compilation-finish-functions' handler publishes the runtime bundle
when the destination directory differs from the source root."
  (let* ((compile-buf (generate-new-buffer " *ghostel-test-compile*"))
         (compilation-finish-functions nil)
         (published nil)
         (default-directory nil)
         (ghostel-module-dir nil)
         (ghostel-module-directory "/custom/dir/"))
    (unwind-protect
        (ghostel-test--without-subr-trampolines
          (cl-letf (((symbol-function 'ghostel--resource-root)
                     (lambda () "/src/ghostel/"))
                    ((symbol-function 'compile)
                     (lambda (&rest _) compile-buf))
                    ((symbol-function 'ghostel--publish-built-module-artifacts)
                     (lambda (source-dir dest-dir)
                       (setq published (list source-dir dest-dir))))
                    ((symbol-function 'message) (lambda (&rest _))))
            (ghostel-module-compile)
            (should (equal 1 (length compilation-finish-functions)))
            ;; Simulate compilation completion.
            (funcall (car compilation-finish-functions) compile-buf "finished\n")
            (should (null compilation-finish-functions))
            (should (equal (list (downcase (expand-file-name "zig-out/bin" "/src/ghostel/"))
                                 (downcase (expand-file-name "/custom/dir/")))
                           (mapcar #'downcase published)))))
      (when (buffer-live-p compile-buf)
        (kill-buffer compile-buf)))))

(ert-deftest ghostel-test-module-compile-no-install-when-dest-same ()
  "When dest matches source, no finish handler is registered."
  (let ((compilation-finish-functions nil)
        (default-directory nil)
        (ghostel-module-directory nil))
    (let ((native-comp-enable-subr-trampolines nil))
      (cl-letf (((symbol-function 'ghostel--resource-root)
                 (lambda () "/src/ghostel/"))
                ((symbol-function 'compile)
                 (lambda (&rest _) (current-buffer))))
        (ghostel-module-compile)
        (should (null compilation-finish-functions))))))

(ert-deftest ghostel-test-module-version-match ()
  "Test that version check does nothing when module meets minimum."
  (let ((warned nil)
        (ghostel--minimum-module-version "0.2.0"))
    (cl-letf (((symbol-function 'ghostel--module-version)
               (lambda () "0.2.0"))
              ((symbol-function 'display-warning)
               (lambda (&rest _) (setq warned t))))
      (ghostel--check-module-version "/tmp")
      (should-not warned))))

(ert-deftest ghostel-test-module-version-mismatch ()
  "Test that version check warns when module is below minimum.
At load time (PROMPT-USER nil) the warning fires but `ghostel--ensure-module'
must NOT be called — that path can prompt or download (issue #231).
At an interactive entry point (PROMPT-USER t) it does run."
  (let ((ghostel--minimum-module-version "0.2.0"))
    (cl-letf (((symbol-function 'ghostel--module-version)
               (lambda () "0.1.0")))
      (let ((warned nil)
            (ensure-called nil))
        (cl-letf (((symbol-function 'display-warning)
                   (lambda (&rest _) (setq warned t)))
                  ((symbol-function 'ghostel--ensure-module)
                   (lambda (dir) (setq ensure-called dir))))
          (ghostel--check-module-version "/tmp")
          (should warned)
          (should-not ensure-called)))
      (let ((warned nil)
            (ensure-called nil))
        (cl-letf (((symbol-function 'display-warning)
                   (lambda (&rest _) (setq warned t)))
                  ((symbol-function 'ghostel--ensure-module)
                   (lambda (dir) (setq ensure-called dir))))
          (ghostel--check-module-version "/tmp" t)
          (should warned)
          (should (equal "/tmp" ensure-called)))))))

(ert-deftest ghostel-test-load-module-no-prompt-at-load-time ()
  "Loading ghostel must never trigger the auto-install path (issue #231).
At load time `ghostel--load-module' must not invoke
`ghostel--ensure-module' or any of its install paths.  Module
installation only happens at interactive entry points
\(`ghostel', `ghostel-download-module', `ghostel-module-compile').

The early-out in `ghostel--load-module' bails when the module is
already loaded, so this test temporarily hides
`ghostel--new' and the `ghostel-module' feature flag to force the
missing-file code path, then restores them."
  (let* ((tmp (make-temp-file "ghostel-test-no-mod" t))
         (ghostel-module-auto-install 'ask)
         (calls '())
         (had-feat (featurep 'ghostel-module))
         (saved-new (and (fboundp 'ghostel--new)
                         (symbol-function 'ghostel--new))))
    (unwind-protect
        (progn
          (when had-feat
            (setq features (delq 'ghostel-module features)))
          (when saved-new
            (fmakunbound 'ghostel--new))
          (cl-letf (((symbol-function 'ghostel--resource-root)
                     (lambda () tmp))
                    ((symbol-function 'ghostel--ensure-module)
                     (lambda (&rest _) (push 'ensure calls)))
                    ((symbol-function 'read-char-choice)
                     (lambda (&rest _) (push 'prompt calls) ?s))
                    ((symbol-function 'ghostel--download-module)
                     (lambda (&rest _) (push 'download calls) nil))
                    ((symbol-function 'ghostel--compile-module)
                     (lambda (&rest _) (push 'compile calls) nil))
                    ((symbol-function 'display-warning)
                     (lambda (&rest _) nil)))
            (ghostel--load-module)
            (ghostel--load-module nil)))
      (delete-directory tmp t)
      (when saved-new
        (fset 'ghostel--new saved-new))
      (when had-feat
        (cl-pushnew 'ghostel-module features)))
    (should (null calls))))

(ert-deftest ghostel-test-module-version-newer-than-minimum ()
  "Test that version check does nothing when module exceeds minimum."
  (let ((warned nil)
        (ghostel--minimum-module-version "0.2.0"))
    (cl-letf (((symbol-function 'ghostel--module-version)
               (lambda () "0.3.0"))
              ((symbol-function 'display-warning)
               (lambda (&rest _) (setq warned t))))
      (ghostel--check-module-version "/tmp")
      (should-not warned))))

(ert-deftest ghostel-test-sidecar-read-missing ()
  "Reading a missing sidecar returns nil."
  (let ((tmp (make-temp-file "ghostel-test-sidecar" t)))
    (unwind-protect
        (should (null (ghostel--read-module-sidecar-version tmp)))
      (delete-directory tmp t))))

(ert-deftest ghostel-test-sidecar-read-empty ()
  "Reading an empty sidecar returns nil."
  (let ((tmp (make-temp-file "ghostel-test-sidecar" t)))
    (unwind-protect
        (progn
          (with-temp-file (ghostel--module-sidecar-path tmp))
          (should (null (ghostel--read-module-sidecar-version tmp))))
      (delete-directory tmp t))))

(ert-deftest ghostel-test-sidecar-round-trip ()
  "Writing then reading the sidecar returns the same version string."
  (let ((tmp (make-temp-file "ghostel-test-sidecar" t)))
    (unwind-protect
        (progn
          (ghostel--write-module-sidecar-version tmp "1.2.3")
          (should (equal "1.2.3" (ghostel--read-module-sidecar-version tmp))))
      (delete-directory tmp t))))

(ert-deftest ghostel-test-sidecar-trims-whitespace ()
  "Trailing whitespace in the sidecar is trimmed by the reader."
  (let ((tmp (make-temp-file "ghostel-test-sidecar" t)))
    (unwind-protect
        (progn
          (with-temp-file (ghostel--module-sidecar-path tmp)
            (insert "  0.9.1  \n\n"))
          (should (equal "0.9.1" (ghostel--read-module-sidecar-version tmp))))
      (delete-directory tmp t))))

(ert-deftest ghostel-test-release-version-from-url ()
  "Parsing a /releases/download/vX.Y.Z/asset URL extracts the version."
  (should (equal
           "0.25.0"
           (ghostel--release-version-from-url
            "https://github.com/owner/repo/releases/download/v0.25.0/ghostel-module-x86_64-linux.so")))
  ;; latest-style URL (server hasn't redirected) — no version embedded.
  (should (null
           (ghostel--release-version-from-url
            "https://github.com/owner/repo/releases/latest/download/ghostel-module-x86_64-linux.so")))
  (should (null (ghostel--release-version-from-url nil))))

(ert-deftest ghostel-test-load-module-skips-stale-sidecar-at-load-time ()
  "When the sidecar reports a stale version, `module-load' must NOT run.
At load time PROMPT-USER is nil so we only warn and skip — no
prompt, no install, no `module-load' of the stale binary."
  (let* ((tmp (make-temp-file "ghostel-test-load-stale" t))
         (mod (expand-file-name (concat "ghostel-module" module-file-suffix)
                                tmp))
         (ghostel--minimum-module-version "0.25.0")
         (load-calls nil)
         (ensure-calls nil)
         (warned nil)
         (had-feat (featurep 'ghostel-module))
         (saved-new (and (fboundp 'ghostel--new)
                         (symbol-function 'ghostel--new))))
    (unwind-protect
        (progn
          (when had-feat
            (setq features (delq 'ghostel-module features)))
          (when saved-new
            (fmakunbound 'ghostel--new))
          (with-temp-file mod (insert "stub"))
          (ghostel--write-module-sidecar-version tmp "0.20.0")
          (cl-letf (((symbol-function 'ghostel--module-directory)
                     (lambda () (file-name-as-directory tmp)))
                    ((symbol-function 'module-load)
                     (lambda (path) (push path load-calls)))
                    ((symbol-function 'ghostel--ensure-module)
                     (lambda (dir) (push dir ensure-calls)))
                    ((symbol-function 'display-warning)
                     (lambda (&rest _) (setq warned t))))
            (ghostel--load-module)
            (should warned)
            (should (null load-calls))
            (should (null ensure-calls))))
      (delete-directory tmp t)
      (when saved-new
        (fset 'ghostel--new saved-new))
      (when had-feat
        (cl-pushnew 'ghostel-module features)))))

(ert-deftest ghostel-test-load-module-prompts-on-stale-sidecar ()
  "Interactive entry with a stale sidecar runs `ghostel--ensure-module'.
After install refreshes the sidecar, the fresh module is loaded
in-process so no Emacs restart is needed."
  (let* ((tmp (make-temp-file "ghostel-test-load-stale-i" t))
         (loader (expand-file-name (concat "dyn-loader-module" module-file-suffix)
                                   tmp))
         (mod (expand-file-name (concat "ghostel-module" module-file-suffix)
                                 tmp))
         (manifest (expand-file-name "ghostel-module.json" tmp))
         (ghostel-module-dir tmp)
         (ghostel--minimum-module-version "0.25.0")
         (system-type 'gnu/linux)
         (runtime-ready nil)
         (load-calls nil)
         (manifest-calls nil)
         (ensure-calls nil)
         (had-feat (featurep 'ghostel-module))
         (had-dyn-feat (featurep 'dyn-loader-module))
         (saved-new (and (fboundp 'ghostel--new)
                         (symbol-function 'ghostel--new)))
         (saved-version (and (fboundp 'ghostel--module-version)
                             (symbol-function 'ghostel--module-version))))
    (unwind-protect
        (progn
           (when had-feat
             (setq features (delq 'ghostel-module features)))
           (when had-dyn-feat
             (setq features (delq 'dyn-loader-module features)))
           (when saved-new
             (fmakunbound 'ghostel--new))
           (when saved-version
             (fmakunbound 'ghostel--module-version))
           (with-temp-file loader (insert "stub"))
           (with-temp-file mod (insert "stub"))
           (with-temp-file manifest (insert "{}"))
           (ghostel--write-module-sidecar-version tmp "0.20.0")
           (cl-letf (((symbol-function 'ghostel--native-runtime-ready-p)
                      (lambda () runtime-ready))
                     ((symbol-function 'ghostel--module-version)
                      (lambda () ghostel--minimum-module-version))
                     ((symbol-function 'module-load)
                      (lambda (path)
                        (push path load-calls)
                        (cl-pushnew 'dyn-loader-module features)))
                     ((symbol-function 'ghostel--loader-load-manifest)
                      (lambda (path)
                        (push path manifest-calls)
                        (cl-pushnew 'ghostel-module features)
                        (setq runtime-ready t)))
                     ;; Simulate a successful install: rewrite the sidecar
                     ;; to the current minimum, leaving the .so in place.
                    ((symbol-function 'ghostel--ensure-module)
                     (lambda (dir)
                       (push dir ensure-calls)
                       (ghostel--write-module-sidecar-version
                        dir ghostel--minimum-module-version)))
                    ((symbol-function 'display-warning)
                     (lambda (&rest _) nil)))
            (ghostel--load-module t)
            (should (equal 1 (length ensure-calls)))
            (should (equal (list loader) load-calls))
            (should (equal (list manifest) manifest-calls))))
      (delete-directory tmp t)
      (when saved-new
        (fset 'ghostel--new saved-new))
      (when saved-version
        (fset 'ghostel--module-version saved-version))
      (if had-feat
          (cl-pushnew 'ghostel-module features)
        (setq features (delq 'ghostel-module features)))
      (if had-dyn-feat
          (cl-pushnew 'dyn-loader-module features)
        (setq features (delq 'dyn-loader-module features))))))

(ert-deftest ghostel-test-load-module-prompts-when-loaded-but-stale ()
  "Stale already-loaded module triggers a prompt at interactive entry.
Issue #256: when no sidecar existed at startup the elisp loader
still mapped the stale .so, and the previous version check ran
with PROMPT-USER nil so only a bare warning was surfaced.  After
the fix `M-x ghostel' must offer the install dialog."
  (let* ((tmp (make-temp-file "ghostel-test-loaded-stale" t))
         (ghostel-module-dir tmp)
         (ghostel--minimum-module-version "0.25.0")
         (system-type 'gnu/linux)
         (warned nil)
         (ensure-calls nil)
         (had-feat (featurep 'ghostel-module))
         (had-dyn-feat (featurep 'dyn-loader-module))
         (runtime-ready t))
    (unwind-protect
        (progn
           ;; Pretend the (stale) module is already loaded.
           (cl-pushnew 'ghostel-module features)
           (cl-pushnew 'dyn-loader-module features)
           (cl-letf (((symbol-function 'ghostel--native-runtime-ready-p)
                      (lambda () runtime-ready))
                     ((symbol-function 'ghostel--module-version)
                      (lambda () "0.20.0"))
                    ((symbol-function 'ghostel--ensure-module)
                     (lambda (dir) (push dir ensure-calls)))
                    ((symbol-function 'display-warning)
                     (lambda (&rest _) (setq warned t))))
            (ghostel--load-module t)
            (should warned)
            (should (equal 1 (length ensure-calls)))))
      (delete-directory tmp t)
      (unless had-feat
        (setq features (delq 'ghostel-module features)))
      (unless had-dyn-feat
        (setq features (delq 'dyn-loader-module features))))))

(ert-deftest ghostel-test-load-module-no-prompt-on-loaded-stale-at-load-time ()
  "Even with a stale loaded module, the load-time call must NOT prompt.
The interactive prompt is gated on PROMPT-USER; load-time
auto-execution (e.g. byte-compile) only warns."
  (let* ((tmp (make-temp-file "ghostel-test-loaded-stale-load" t))
         (ghostel--minimum-module-version "0.25.0")
         (ensure-calls nil)
         (had-feat (featurep 'ghostel-module)))
    (unwind-protect
        (progn
          (cl-pushnew 'ghostel-module features)
          (cl-letf (((symbol-function 'ghostel--module-directory)
                     (lambda () (file-name-as-directory tmp)))
                    ((symbol-function 'ghostel--module-version)
                     (lambda () "0.20.0"))
                    ((symbol-function 'ghostel--ensure-module)
                     (lambda (dir) (push dir ensure-calls)))
                    ((symbol-function 'display-warning)
                     (lambda (&rest _) nil)))
            (ghostel--load-module)
            (should (null ensure-calls))))
      (delete-directory tmp t)
      (unless had-feat
        (setq features (delq 'ghostel-module features))))))

(ert-deftest ghostel-test-install-module-pair-deletes-stale-sidecar ()
  "Existing dest sidecar is removed before the new module is moved.
`ghostel--install-module-pair' keeps the invariant that a fresh
module is never paired with a stale sidecar."
  (let* ((src (make-temp-file "ghostel-test-pair-src" t))
         (dst (make-temp-file "ghostel-test-pair-dst" t))
         (built-mod (expand-file-name "ghostel-module.so" src))
         (final-mod (expand-file-name "ghostel-module.so" dst))
         (built-sidecar (expand-file-name "ghostel-module.version" src))
         (final-sidecar (expand-file-name "ghostel-module.version" dst)))
    (unwind-protect
        (progn
          (with-temp-file built-mod (insert "new-so"))
          (with-temp-file built-sidecar (insert "0.99.0\n"))
          (with-temp-file final-sidecar (insert "0.10.0\n"))
          (ghostel--install-module-pair built-mod final-mod
                                        built-sidecar final-sidecar)
          (should (file-exists-p final-mod))
          (should (equal "new-so" (with-temp-buffer
                                    (insert-file-contents final-mod)
                                    (buffer-string))))
          (should (equal "0.99.0" (ghostel--read-module-sidecar-version dst)))
          (should-not (file-exists-p built-mod))
          (should-not (file-exists-p built-sidecar)))
      (delete-directory src t)
      (delete-directory dst t))))

(ert-deftest ghostel-test-install-module-pair-sidecar-failure-leaves-absent ()
  "A sidecar rename failure leaves the dest in `absent' state.
The pre-delete in `ghostel--install-module-pair' guarantees that if
the second rename fails, the destination has a fresh module but
NO sidecar — which the loader treats as backward-compat live check,
not as `refuse to map'."
  (let* ((src (make-temp-file "ghostel-test-pair-fail-src" t))
         (dst (make-temp-file "ghostel-test-pair-fail-dst" t))
         (built-mod (expand-file-name "ghostel-module.so" src))
         (final-mod (expand-file-name "ghostel-module.so" dst))
         (built-sidecar (expand-file-name "ghostel-module.version" src))
         (final-sidecar (expand-file-name "ghostel-module.version" dst))
         (real-rename (symbol-function 'rename-file)))
    (unwind-protect
        (progn
          (with-temp-file built-mod (insert "new-so"))
          (with-temp-file built-sidecar (insert "0.99.0\n"))
          (with-temp-file final-sidecar (insert "0.10.0\n"))
          (cl-letf (((symbol-function 'rename-file)
                     (lambda (from to &optional ok)
                       (if (string-suffix-p ".version" from)
                           (signal 'file-error '("simulated sidecar rename failure"))
                         (funcall real-rename from to ok)))))
            (should-error
             (ghostel--install-module-pair built-mod final-mod
                                           built-sidecar final-sidecar)
             :type 'file-error))
          ;; Fresh module landed.
          (should (file-exists-p final-mod))
          (should (equal "new-so" (with-temp-buffer
                                    (insert-file-contents final-mod)
                                    (buffer-string))))
          ;; Stale sidecar was pre-deleted, new sidecar rename failed —
          ;; net result is `absent', not `stale'.
          (should-not (file-exists-p final-sidecar)))
      (delete-directory src t)
      (delete-directory dst t))))

(ert-deftest ghostel-test-download-module-deletes-stale-sidecar-on-failure ()
  "A failed download leaves no stale sidecar behind.
The download path pre-deletes the dest sidecar so that even if
`ghostel--download-file' fails, the loader falls back to the live
version check on whatever module is on disk instead of refusing
to map it based on stale sidecar metadata."
  (let* ((dir (make-temp-file "ghostel-test-dl-fail" t))
         (sidecar (ghostel--module-sidecar-path dir)))
    (unwind-protect
        (progn
          (with-temp-file sidecar (insert "0.10.0\n"))
          (cl-letf (((symbol-function 'ghostel--download-file)
                     (lambda (&rest _) nil))
                    ((symbol-function 'message) (lambda (&rest _))))
            (should-not (ghostel--download-module dir)))
          (should-not (file-exists-p sidecar)))
      (delete-directory dir t))))

(ert-deftest ghostel-test-build-emits-sidecar-version ()
  "`zig build' writes a sidecar matching the live module version.
Runs in the native test suite so the build has already produced
both the .so/.dylib and ghostel-module.version next to it."
  :tags '(native)
  (let* ((dir (ghostel--module-directory))
         (sidecar (ghostel--read-module-sidecar-version dir)))
    (should (stringp sidecar))
    (should (equal sidecar (ghostel--module-version)))))

(ert-deftest ghostel-test-platform-tag-normalizes-arch ()
  "Test that amd64/arm64 arch names are normalized in platform tags."
  ;; amd64 -> x86_64
  (let ((system-configuration "amd64-pc-linux-gnu")
        (system-type 'gnu/linux))
    (should (equal (ghostel--module-platform-tag) "x86_64-linux")))
  ;; arm64 -> aarch64
  (let ((system-configuration "arm64-apple-darwin23.1.0")
        (system-type 'darwin))
    (should (equal (ghostel--module-platform-tag) "aarch64-macos")))
  ;; x86_64 unchanged
  (let ((system-configuration "x86_64-pc-linux-gnu")
        (system-type 'gnu/linux))
    (should (equal (ghostel--module-platform-tag) "x86_64-linux")))
  ;; aarch64 unchanged
  (let ((system-configuration "aarch64-unknown-linux-gnu")
        (system-type 'gnu/linux))
    (should (equal (ghostel--module-platform-tag) "aarch64-linux"))))

(ert-deftest ghostel-test-module-platform-tag-windows ()
  "Windows builds use the release tag format expected by Ghostel assets."
  (let ((system-type 'windows-nt)
        (system-configuration "x86_64-w64-mingw32"))
    (should (equal "x86_64-windows"
                   (ghostel--module-platform-tag)))))

(ert-deftest ghostel-test-module-asset-name-windows ()
  "Windows module assets use the Windows platform tag in their file name."
  (let ((system-type 'windows-nt)
        (system-configuration "x86_64-w64-mingw32")
        (module-file-suffix ".dll"))
    (should (equal "ghostel-module-x86_64-windows.tar.xz"
                   (ghostel--module-asset-name)))))

(ert-deftest ghostel-test-start-process-windows-conpty-skips-shell-wrapper ()
  "Windows ConPTY startup passes the shell directly."
  (with-temp-buffer
    (let ((system-type 'windows-nt)
          (ghostel-shell "C:/Program Files/Emacs/cmdproxy.exe")
          (ghostel-shell-integration nil)
          (default-directory "C:/ghostel/")
          (ghostel--term 'fake-term)
          (ghostel--term-cols nil)
          (ghostel--term-rows nil)
          (captured-command nil))
      (ghostel-test--without-subr-trampolines
        (cl-letf (((symbol-function 'window-body-height)
                   (lambda (&optional _) 33))
                  ((symbol-function 'window-max-chars-per-line)
                   (lambda (&optional _) 80))
                  ((symbol-function 'ghostel--resource-root)
                   (lambda () "C:/ghostel/"))
                  ((symbol-function 'make-pipe-process)
                   (lambda (&rest _) 'fake-proc))
                  ((symbol-function 'process-put)
                   (lambda (&rest _) nil))
                  ((symbol-function 'set-process-query-on-exit-flag)
                   (lambda (&rest _) nil))
                  ((symbol-function 'conpty--init)
                   (lambda (_term _proc command _rows _cols _cwd _env)
                     (setq captured-command command)
                     t)))
          (should (eq 'fake-proc (ghostel--start-process)))
          (should (equal (combine-and-quote-strings (list ghostel-shell) " ")
                         captured-command))
          (should-not (string-match-p "/bin/sh" captured-command)))))))

(ert-deftest ghostel-test-windows-ghostel-starts ()
  "Windows `ghostel' loads the native runtime and starts ConPTY."
  :tags '(native)
  (skip-unless (eq system-type 'windows-nt))
  (let ((shell (getenv "SHELL")))
    (skip-unless (not (and shell (string-prefix-p "/" shell)))))
  (let* ((buffer-name (generate-new-buffer-name " *ghostel-startup-test*"))
         (ghostel-buffer-name buffer-name)
         (ghostel-shell-integration nil)
         (buf nil))
    (with-timeout (10 (ert-fail "Timed out starting Windows Ghostel"))
      (setq buf (ghostel))
      (should (buffer-live-p buf))
      (with-current-buffer buf
        (should (derived-mode-p 'ghostel-mode))
        (should ghostel--term)
        (should (processp ghostel--process))
        (should (ghostel--native-runtime-ready-p))
        (should (ghostel--native-runtime-reloadable-p))
        (should (featurep 'dyn-loader-module))
        (should (member ghostel--module-id
                        (ghostel--loader-loaded-modules)))
        (should (member ghostel--conpty-module-id
                        (ghostel--loader-loaded-modules)))
        (should (fboundp 'ghostel--new))
        (should (fboundp 'conpty--init))))))

(ert-deftest ghostel-test-download-module-prefix-rejects-too-old-version ()
  "Prefix download rejects versions below the minimum supported module version."
  (let ((ghostel--minimum-module-version "0.7.1"))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (_) nil))
                ((symbol-function 'read-string)
                 (lambda (&rest _) "0.7.0")))
        (should-error (ghostel-download-module '(4))
                      :type 'user-error)))))

(ert-deftest ghostel-test-module-file-path-uses-custom-dir ()
  "Custom module directories override the default module path."
  (let* ((module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll"))
    (should (equal (downcase (ghostel-test--fixture-path module-dir "ghostel-module.dll"))
                   (downcase (ghostel--target-module-file-path))))))

(ert-deftest ghostel-test-download-module-publishes-downloaded-archive ()
  "Module downloads publish the downloaded archive into the chosen module directory."
  (let* ((module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (source-dir (ghostel-test--fixture-dir "ghostel-build"))
         (archive (ghostel-test--fixture-path source-dir
                                              "ghostel-module-x86_64-windows.tar.xz"))
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (download-dest nil)
         (published nil))
    (cl-letf (((symbol-function 'ghostel--module-download-url)
               (lambda (&optional _version)
                 "https://example.invalid/releases/download/v0.7.1/ghostel-module-x86_64-windows.tar.xz"))
              ((symbol-function 'ghostel--download-file)
               (lambda (_url dest)
                 (setq download-dest dest)
                 "https://example.invalid/releases/download/v0.7.1/ghostel-module-x86_64-windows.tar.xz"))
              ((symbol-function 'ghostel--publish-downloaded-module-archive)
               (lambda (archive dir)
                 (setq published (list archive dir))
                 t))
              ((symbol-function 'ghostel--write-module-sidecar-version)
               (lambda (&rest _) nil))
              ((symbol-function 'delete-file)
               (lambda (&rest _) nil))
              ((symbol-function 'make-directory)
               (lambda (&rest _) nil))
              ((symbol-function 'message)
               (lambda (&rest _) nil)))
      (should (ghostel--download-module source-dir))
      (should (equal (downcase archive)
                     (downcase download-dest)))
      (should (equal (list (downcase archive)
                           (downcase source-dir))
                     (list (downcase (car published))
                           (downcase (cadr published))))))))

(ert-deftest ghostel-test-extract-module-archive-uses-tar-xf ()
  "Downloaded module archives are unpacked with tar."
  (let ((invocation nil))
    (cl-letf (((symbol-function 'process-file)
               (lambda (program infile buffer display &rest args)
                 (setq invocation (list program infile buffer display args))
                 0)))
      (ghostel--extract-module-archive "C:/ghostel/ghostel-module-x86_64-windows.tar.xz"
                                       "C:/ghostel/staging/")
      (should (equal '("tar" nil "*ghostel-download*" nil
                       ("xJf" "C:/ghostel/ghostel-module-x86_64-windows.tar.xz"
                        "-C" "C:/ghostel/staging/"))
                     invocation)))))

(ert-deftest ghostel-test-replace-module-file-deletes-before-rotating ()
  "Replacement deletes DEST first and only rotates when delete fails."
  (let* ((src "C:/ghostel/build/ghostel-module.dll")
         (dest "C:/ghostel/live/ghostel-module.dll")
         (backup (concat dest ".bak"))
         (deletes nil)
         (renames nil)
         (copies nil)
         (system-type 'gnu/linux))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase dest)
                                 (downcase backup)))))
                ((symbol-function 'delete-file)
                 (lambda (path &optional _trash)
                   (push path deletes)
                   (signal 'file-error (list "in use" path))))
                ((symbol-function 'rename-file)
                 (lambda (from to &optional ok-if-already-exists)
                   (push (list from to ok-if-already-exists) renames)))
                ((symbol-function 'copy-file)
                 (lambda (from to &optional ok-if-already-exists)
                   (push (list from to ok-if-already-exists) copies))))
        (ghostel--replace-module-file src dest)
        (should (equal (list dest) deletes))
        (should (equal (list (list dest (concat dest ".1.bak") t)) renames))
        (should (equal (list (list src dest t)) copies))))))

(ert-deftest ghostel-test-publish-downloaded-module-archive-preserves-existing-windows-backups ()
  "Downloading on Windows uses a fresh .bak name when an older backup remains."
  (let* ((archive "C:/ghostel/ghostel-module-x86_64-windows.tar.xz")
         (staging-dir (ghostel-test--fixture-dir "ghostel-staging"))
         (module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (loader-src (ghostel-test--fixture-path staging-dir "dyn-loader-module.dll"))
         (target-src (ghostel-test--fixture-path staging-dir "ghostel-module.dll"))
         (conpty-src (ghostel-test--fixture-path staging-dir "conpty-module.dll"))
         (loader-dest (ghostel-test--fixture-path module-dir "dyn-loader-module.dll"))
         (target-dest (ghostel-test--fixture-path module-dir "ghostel-module.dll"))
         (conpty-dest (ghostel-test--fixture-path module-dir "conpty-module.dll"))
         (loader-backup (concat loader-dest ".bak"))
         (target-backup (concat target-dest ".bak"))
         (conpty-backup (concat conpty-dest ".bak"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (extracted nil)
         (deletes nil)
         (renames nil)
         (copies nil)
         (metadata-writes nil)
         (cleaned nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'make-temp-file)
                 (lambda (_prefix &optional _dir-flag)
                   staging-dir))
                ((symbol-function 'ghostel--extract-module-archive)
                 (lambda (actual-archive actual-dir)
                   (setq extracted (list actual-archive actual-dir))))
                ((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase loader-src)
                                 (downcase target-src)
                                 (downcase conpty-src)
                                 (downcase loader-dest)
                                 (downcase target-dest)
                                 (downcase conpty-dest)
                                 (downcase loader-backup)
                                 (downcase target-backup)
                                 (downcase conpty-backup)))))
                ((symbol-function 'file-directory-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase staging-dir)
                                 (downcase module-dir)))))
                ((symbol-function 'delete-file)
                 (lambda (path &optional _trash)
                   (push path deletes)
                   (signal 'file-error (list "in use" path))))
                ((symbol-function 'rename-file)
                 (lambda (src dest &optional ok-if-already-exists)
                   (push (list src dest ok-if-already-exists) renames)))
                ((symbol-function 'copy-file)
                 (lambda (src dest &optional ok-if-already-exists)
                   (push (list src dest ok-if-already-exists) copies)))
                ((symbol-function 'ghostel--write-loader-metadata-atomically)
                 (lambda (manifest-file _dir _meta)
                   (push manifest-file metadata-writes)))
                ((symbol-function 'delete-directory)
                 (lambda (path recursive)
                   (setq cleaned (list path recursive)))))
        (should (ghostel--publish-downloaded-module-archive archive module-dir))
        (should (equal (list archive staging-dir) extracted))
        (should (equal 3 (length deletes)))
        (should (member (list loader-dest (concat loader-dest ".1.bak") t) renames))
        (should (member (list target-dest (concat target-dest ".1.bak") t) renames))
        (should (member (list conpty-dest (concat conpty-dest ".1.bak") t) renames))
        (should (equal 3 (length copies)))
        (should (equal '("conpty-module.json" "ghostel-module.json")
                       (sort metadata-writes #'string<)))
        (should (equal (list staging-dir t) cleaned))))))

(ert-deftest ghostel-test-ask-install-action-includes-compile-for-custom-dir ()
  "Missing-module prompts still offer compile for custom module dirs."
  (let ((ghostel-module-dir "C:/modules/")
        (choice nil))
    (cl-letf (((symbol-function 'read-char-choice)
               (lambda (_prompt chars)
                 (setq choice chars)
                 ?c)))
      (should (eq 'compile (ghostel--ask-install-action "C:/modules/")))
      (should (equal '(?d ?c ?s) choice)))))

(ert-deftest ghostel-test-conpty-module-file-path-ignores-custom-dir-when-omitted ()
  "The default ConPTY module path comes from the package directory, not `ghostel-module-dir'."
  (let* ((module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (package-dir (ghostel-test--fixture-dir "ghostel-package"))
         (package-path (ghostel-test--fixture-path package-dir "ghostel.el"))
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (load-file-name nil)
         (buffer-file-name nil))
    (cl-letf (((symbol-function 'locate-library)
               (lambda (library &optional _nosuffix _path _interactive-call)
                 (when (equal library "ghostel")
                   package-path))))
      (should (equal (downcase (ghostel-test--fixture-path package-dir "conpty-module.dll"))
                     (downcase (ghostel--conpty-module-file-path)))))))

(ert-deftest ghostel-test-source-groups-conpty-backend-before-internal-variables ()
  "Windows ConPTY helpers live under the dedicated backend section."
  (let* ((source (ghostel-test--ghostel-source))
         (download-pos (ghostel-test--source-pos
                        source
                        ";;; Automatic download and compilation of native module"))
         (backend-pos (ghostel-test--source-pos
                       source
                       ";;; Windows ConPTY backend"))
         (transport-pos (ghostel-test--source-pos
                         source
                         ";;; Transport abstraction"))
         (internal-pos (ghostel-test--source-pos
                        source
                        ";;; Internal variables")))
    (should download-pos)
    (should backend-pos)
    (should transport-pos)
    (should internal-pos)
    (should (< download-pos backend-pos internal-pos))
    (should (< backend-pos transport-pos internal-pos))
    (dolist (marker '("(declare-function conpty--init \"conpty-module\")"
                      "(defvar-local ghostel--conpty-notify-pipe nil"
                      "(defun ghostel--conpty-module-file-path"
                      "(defun ghostel--native-runtime-ready-p"
                      "(defun ghostel--conpty-active-p"
                      "(defun ghostel--conpty-filter"
                      "(defun ghostel--start-process-windows"))
      (let ((pos (ghostel-test--source-pos source marker)))
        (should pos)
        (should (< backend-pos pos internal-pos))))
    (should-not (string-match-p "(defun ghostel--ensure-conpty-loaded" source))
    (should-not (string-match-p "Permanent transport wrapper" source))))

(ert-deftest ghostel-test-source-start-process-uses-shared-state-helper ()
  "Both process-start backends share startup state."
  (let ((source (ghostel-test--ghostel-source)))
    (should (ghostel-test--source-pos source "(defun ghostel--start-process-state ()"))
    (should (ghostel-test--source-pos source "(defun ghostel--start-process-windows (state)"))
    (should (ghostel-test--source-pos source "(ghostel--start-process-state)"))
    (should (ghostel-test--source-pos source "(ghostel--start-process-windows"))
    (should (ghostel-test--source-pos
             source
             "(plist-put (copy-sequence state) :env-overrides process-environment)"))))

(ert-deftest ghostel-test-load-module-if-available-loads-loader-managed-windows-runtime ()
  "Windows bootstrap loads both manifests through dyn-loader."
  (let* ((module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (loader-path (ghostel-test--fixture-path module-dir "dyn-loader-module.dll"))
         (ghostel-manifest (ghostel-test--fixture-path module-dir "ghostel-module.json"))
         (ghostel-module (ghostel-test--fixture-path module-dir "ghostel-module.dll"))
         (conpty-manifest (ghostel-test--fixture-path module-dir "conpty-module.json"))
         (conpty-module (ghostel-test--fixture-path module-dir "conpty-module.dll"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (loaded nil)
         (manifests nil)
         (checked nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase loader-path)
                                 (downcase ghostel-manifest)
                                 (downcase ghostel-module)
                                 (downcase conpty-manifest)
                                 (downcase conpty-module)))))
                ((symbol-function 'module-load)
                 (lambda (path)
                   (push path loaded)))
                ((symbol-function 'ghostel--loader-load-manifest)
                 (lambda (path)
                   (push path manifests)))
                ((symbol-function 'ghostel--read-module-sidecar-version)
                 (lambda (&rest _) ghostel--minimum-module-version))
                ((symbol-function 'ghostel--check-module-version)
                 (lambda (dir &optional _prompt-user)
                   (setq checked dir))))
        (should (ghostel--load-module-if-available))
        (should (equal (list (downcase loader-path))
                       (mapcar #'downcase (reverse loaded))))
        (should (equal (list (downcase ghostel-manifest)
                             (downcase conpty-manifest))
                       (mapcar #'downcase (reverse manifests))))
        (should (equal (downcase module-dir)
                       (downcase checked)))))))

(ert-deftest ghostel-test-load-module-does-not-accept-direct-loaded-runtime ()
  "Direct-loaded native exports do not satisfy runtime readiness on any OS."
  (dolist (os '(gnu/linux darwin windows-nt))
    (let ((system-type os)
          (initialized nil)
          (original-featurep (symbol-function 'featurep)))
      (ghostel-test--without-subr-trampolines
        (cl-letf (((symbol-function 'ghostel--new)
                   (lambda (&rest _) nil))
                  ((symbol-function 'conpty--init)
                   (lambda (&rest _) nil))
                  ((symbol-function 'featurep)
                   (lambda (feature)
                     (or (memq feature '(ghostel-module conpty-module))
                         (and (not (eq feature 'dyn-loader-module))
                              (funcall original-featurep feature))))))
          (should-not (ghostel--native-runtime-ready-p))
          (cl-letf (((symbol-function 'ghostel--native-runtime-reloadable-p)
                     (lambda () initialized))
                    ((symbol-function 'ghostel--initialize-native-modules)
                     (lambda (&optional prompt-user)
                       (setq initialized prompt-user)))
                    ((symbol-function 'ghostel--check-module-version)
                     (lambda (&rest _) nil)))
            (ghostel--load-module t)
            (should initialized)))))))

(ert-deftest ghostel-test-load-module-if-available-requires-full-windows-runtime-bundle ()
  "Windows bootstrap skips loading when any runtime DLL is missing."
  (let* ((module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (loader-path (ghostel-test--fixture-path module-dir "dyn-loader-module.dll"))
         (ghostel-manifest (ghostel-test--fixture-path module-dir "ghostel-module.json"))
         (ghostel-module (ghostel-test--fixture-path module-dir "ghostel-module.dll"))
         (conpty-manifest (ghostel-test--fixture-path module-dir "conpty-module.json"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (loaded nil)
         (bootstrapped nil)
         (checked nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase loader-path)
                                 (downcase ghostel-manifest)
                                 (downcase ghostel-module)
                                 (downcase conpty-manifest)))))
                ((symbol-function 'ghostel--ensure-loader-loaded)
                 (lambda (_path)
                   (setq loaded t)))
                ((symbol-function 'ghostel--bootstrap-native-runtime)
                 (lambda (_dir)
                   (setq bootstrapped t)))
                ((symbol-function 'ghostel--check-module-version)
                 (lambda (&rest _)
                   (setq checked t))))
        (should-not (ghostel--load-module-if-available))
        (should-not loaded)
        (should-not bootstrapped)
        (should-not checked)))))

(ert-deftest ghostel-test-initialize-native-modules-requires-full-windows-runtime-bundle ()
  "Windows startup requires the loader and every runtime manifest."
  (let* ((module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (loader-path (ghostel-test--fixture-path module-dir "dyn-loader-module.dll"))
         (ghostel-manifest (ghostel-test--fixture-path module-dir "ghostel-module.json"))
         (conpty-manifest (ghostel-test--fixture-path module-dir "conpty-module.json"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (noninteractive nil)
         (ensured nil)
         (loaded nil)
         (warnings nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase loader-path)
                                 (downcase ghostel-manifest)))))
                ((symbol-function 'ghostel--ensure-module)
                 (lambda (dir)
                   (setq ensured dir)
                   nil))
                ((symbol-function 'ghostel--load-module-if-available)
                 (lambda (&rest _)
                   (setq loaded t)
                   t))
                ((symbol-function 'display-warning)
                 (lambda (_type message &rest _args)
                   (push message warnings))))
        (let ((err (should-error (ghostel--initialize-native-modules t)
                                 :type 'user-error)))
          (should (string-match-p (regexp-quote conpty-manifest)
                                  (error-message-string err))))
        (should (equal (downcase module-dir) (downcase ensured)))
        (should-not loaded)
        (should-not warnings)))))

(ert-deftest ghostel-test-initialize-native-modules-requires-conpty-module-dll-on-windows ()
  "Windows startup requires the ConPTY DLL even when manifests exist."
  (let* ((module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (loader-path (ghostel-test--fixture-path module-dir "dyn-loader-module.dll"))
         (ghostel-manifest (ghostel-test--fixture-path module-dir "ghostel-module.json"))
         (ghostel-module (ghostel-test--fixture-path module-dir "ghostel-module.dll"))
         (conpty-manifest (ghostel-test--fixture-path module-dir "conpty-module.json"))
         (conpty-module (ghostel-test--fixture-path module-dir "conpty-module.dll"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (noninteractive nil)
         (ensured nil)
         (loaded nil)
         (warnings nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase loader-path)
                                 (downcase ghostel-manifest)
                                 (downcase ghostel-module)
                                 (downcase conpty-manifest)))))
                ((symbol-function 'ghostel--ensure-module)
                 (lambda (dir)
                   (setq ensured dir)
                   nil))
                ((symbol-function 'ghostel--load-module-if-available)
                 (lambda (&rest _)
                   (setq loaded t)
                   t))
                ((symbol-function 'display-warning)
                 (lambda (_type message &rest _args)
                   (push message warnings))))
        (let ((err (should-error (ghostel--initialize-native-modules t)
                                 :type 'user-error)))
          (should (string-match-p (regexp-quote conpty-module)
                                  (error-message-string err))))
        (should (equal module-dir ensured))
        (should-not loaded)
        (should-not warnings)))))

(ert-deftest ghostel-test-compile-module-publishes-module-and-conpty ()
  "Windows compilation publishes build artifacts into the module directory."
  (let* ((source-dir (ghostel-test--fixture-dir "ghostel-build"))
         (build-dir (ghostel-test--fixture-path source-dir "zig-out/bin"))
         (module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (published nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'process-file)
                 (lambda (&rest _) 0))
                ((symbol-function 'ghostel--resource-root)
                 (lambda () source-dir))
                ((symbol-function 'ghostel--publish-built-module-artifacts)
                 (lambda (src dest)
                   (setq published (list src dest))
                   t))
                ((symbol-function 'message)
                 (lambda (&rest _) nil)))
        (should (ghostel--compile-module module-dir))
        (should (equal (list build-dir module-dir) published))))))

(ert-deftest ghostel-test-publish-built-module-artifacts-rotates-existing-windows-modules ()
  "Publishing rotates loaded DLLs to .bak on Windows before copying replacements."
  (let* ((source-dir (ghostel-test--fixture-dir "ghostel-build"))
         (module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (loader-src (ghostel-test--fixture-path source-dir "dyn-loader-module.dll"))
         (module-src (ghostel-test--fixture-path source-dir "ghostel-module.dll"))
         (conpty-src (ghostel-test--fixture-path source-dir "conpty-module.dll"))
         (loader-dest (ghostel-test--fixture-path module-dir "dyn-loader-module.dll"))
         (module-dest (ghostel-test--fixture-path module-dir "ghostel-module.dll"))
         (conpty-dest (ghostel-test--fixture-path module-dir "conpty-module.dll"))
         (loader-backup (concat loader-dest ".bak"))
         (loader-rotated-backup (concat loader-dest ".1.bak"))
         (module-backup (concat module-dest ".bak"))
         (module-rotated-backup (concat module-dest ".1.bak"))
         (conpty-backup (concat conpty-dest ".bak"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll")
         (deletes nil)
         (copies nil)
         (renames nil)
         (metadata-writes nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase loader-src)
                                 (downcase module-src)
                                 (downcase conpty-src)
                                 (downcase loader-dest)
                                 (downcase module-dest)
                                 (downcase conpty-dest)
                                 (downcase loader-backup)
                                 (downcase module-backup)))))
                ((symbol-function 'delete-file)
                 (lambda (path &optional _trash)
                   (push path deletes)
                   (signal 'file-error (list "in use" path))))
                ((symbol-function 'rename-file)
                 (lambda (src dest &optional ok-if-already-exists)
                   (push (list src dest ok-if-already-exists) renames)))
                ((symbol-function 'copy-file)
                 (lambda (src dest &optional ok-if-already-exists)
                   (push (list src dest ok-if-already-exists) copies)))
                ((symbol-function 'ghostel--write-loader-metadata-atomically)
                 (lambda (manifest-file dir metadata)
                   (push (list manifest-file dir metadata) metadata-writes))))
        (should (ghostel--publish-built-module-artifacts source-dir module-dir))
        (should (equal (list conpty-dest module-dest loader-dest) deletes))
        (should (member (list (downcase loader-dest)
                              (downcase loader-rotated-backup)
                              t)
                        (mapcar (lambda (entry)
                                  (list (downcase (nth 0 entry))
                                        (downcase (nth 1 entry))
                                        (nth 2 entry)))
                                renames)))
        (should (member (list (downcase module-dest)
                              (downcase module-rotated-backup)
                              t)
                        (mapcar (lambda (entry)
                                  (list (downcase (nth 0 entry))
                                        (downcase (nth 1 entry))
                                        (nth 2 entry)))
                                renames)))
        (should (member (list (downcase conpty-dest)
                              (downcase conpty-backup)
                              t)
                        (mapcar (lambda (entry)
                                  (list (downcase (nth 0 entry))
                                        (downcase (nth 1 entry))
                                        (nth 2 entry)))
                                renames)))
        (should (equal 3 (length copies)))
        (should (equal (list (list "conpty-module.json"
                                   module-dir
                                   (ghostel--loader-metadata-alist "conpty-module.dll"))
                             (list "ghostel-module.json"
                                   module-dir
                                   (ghostel--loader-metadata-alist "ghostel-module.dll")))
                       metadata-writes))))))

(ert-deftest ghostel-test-publish-built-module-artifacts-errors-when-conpty-missing ()
  "Windows publishing fails loudly when conpty-module.dll is absent."
  (let* ((source-dir (ghostel-test--fixture-dir "ghostel-build"))
         (module-dir (ghostel-test--fixture-dir "ghostel-modules"))
         (loader-src (ghostel-test--fixture-path source-dir "dyn-loader-module.dll"))
         (module-src (ghostel-test--fixture-path source-dir "ghostel-module.dll"))
         (system-type 'windows-nt)
         (ghostel-module-dir module-dir)
         (module-file-suffix ".dll"))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (path)
                   (member (downcase path)
                           (list (downcase loader-src)
                                 (downcase module-src)))))
                ((symbol-function 'file-directory-p)
                 (lambda (_path) t))
                ((symbol-function 'ghostel--replace-module-file)
                 (lambda (&rest _) nil)))
        (let ((err (should-error (ghostel--publish-built-module-artifacts
                                  source-dir module-dir)
                                 :type 'error)))
          (should (string-match-p "Built Windows ConPTY module is missing"
                                  (cadr err))))))))

(ert-deftest ghostel-test-load-module-if-available-skips-when-module-missing ()
  "Missing loader and target module leaves the native module unavailable."
  (let ((ghostel-module-dir "C:/modules/")
        (module-file-suffix ".dll"))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (_path) nil))
                ((symbol-function 'module-load)
                 (lambda (&rest _)
                   (error "Should not load when the module is missing")))
                ((symbol-function 'ghostel--check-module-version)
                 (lambda (&rest _)
                   (error "Should not check version when the module is missing"))))
        (should-not (ghostel--load-module-if-available))))))

(ert-deftest ghostel-test-reload-module-reloads-windows-runtime-bundle ()
  "Windows reload refreshes both loader-managed module ids."
  (let ((system-type 'windows-nt)
        (reloaded nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'ghostel--live-buffers) (lambda () nil))
                ((symbol-function 'ghostel--native-runtime-reloadable-p)
                 (lambda () t))
                ((symbol-function 'ghostel--loader-reload)
                 (lambda (module-id)
                   (push module-id reloaded)))
                ((symbol-function 'garbage-collect)
                 (lambda () nil))
                ((symbol-function 'message)
                 (lambda (&rest _) nil)))
        (ghostel-reload-module)
        (should (equal '("ghostel" "conpty-module")
                       (reverse reloaded)))))))

(ert-deftest ghostel-test-reload-module-recovers-missing-loader-registration ()
  "Reload loads missing runtime manifests before refreshing all module ids."
  (dolist (case '((("ghostel") ("conpty-module.json"))
                  (("conpty-module") ("ghostel-module.json"))
                  (nil ("ghostel-module.json" "conpty-module.json"))))
    (let ((system-type 'windows-nt)
          (module-file-suffix ".dll")
          (ghostel-module-dir "C:/ghostel/")
          (loaded-modules (copy-sequence (car case)))
          (expected-manifests (cadr case))
          (loaded-manifests nil)
          (reloaded nil)
          (original-featurep (symbol-function 'featurep)))
      (ghostel-test--without-subr-trampolines
        (cl-letf (((symbol-function 'featurep)
                   (lambda (feature)
                     (or (eq feature 'dyn-loader-module)
                         (funcall original-featurep feature))))
                  ((symbol-function 'dyn-loader-reload)
                   (lambda (module-id)
                     (push module-id reloaded)))
                  ((symbol-function 'dyn-loader-load-manifest)
                   (lambda (&rest _) t))
                  ((symbol-function 'ghostel--loader-loaded-modules)
                   (lambda () loaded-modules))
                  ((symbol-function 'ghostel--loader-load-manifest)
                   (lambda (manifest)
                     (push manifest loaded-manifests)
                     (cond
                      ((string-suffix-p "ghostel-module.json" manifest)
                       (push "ghostel" loaded-modules))
                      ((string-suffix-p "conpty-module.json" manifest)
                       (push "conpty-module" loaded-modules)))))
                  ((symbol-function 'ghostel--live-buffers)
                   (lambda () nil))
                  ((symbol-function 'garbage-collect)
                   (lambda () nil)))
          (ghostel--reload-native-runtime)
          (should (equal (mapcar (lambda (manifest)
                                   (expand-file-name manifest "C:/ghostel/"))
                                 expected-manifests)
                         (reverse loaded-manifests)))
          (should (equal '("ghostel" "conpty-module")
                         (reverse reloaded))))))))

(ert-deftest ghostel-test-reload-module-closes-live-buffers-before-reload ()
  "Reloading closes live terminals and collects finalizers before module reload."
  (let ((system-type 'windows-nt)
        (events nil))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'ghostel--live-buffers)
                 (lambda () '(live-buffer)))
                ((symbol-function 'ghostel--native-runtime-reloadable-p)
                 (lambda () t))
                ((symbol-function 'ghostel--close-live-buffers)
                 (lambda (buffers)
                   (should (equal '(live-buffer) buffers))
                   (setq events (append events '(close)))))
                ((symbol-function 'garbage-collect)
                 (lambda ()
                   (setq events (append events '(gc)))
                   nil))
                ((symbol-function 'ghostel--loader-reload)
                 (lambda (module-id)
                   (setq events
                         (append events
                                 (list (format "reload:%s" module-id)))))))
        (ghostel--reload-native-runtime)
        (should (equal '(close gc "reload:ghostel" "reload:conpty-module")
                       events))))))



(ert-deftest ghostel-test-module-download-url-uses-minimum-version ()
  "Module downloads pin to the minimum supported native module version."
  (let ((ghostel-github-release-url "https://example.invalid/releases")
        (ghostel--minimum-module-version "0.7.1"))
    (cl-letf (((symbol-function 'ghostel--module-asset-name)
               (lambda () "ghostel-module-x86_64-windows.tar.xz")))
      (should (equal "https://example.invalid/releases/download/v0.7.1/ghostel-module-x86_64-windows.tar.xz"
                     (ghostel--module-download-url ghostel--minimum-module-version))))))

(ert-deftest ghostel-test-download-module-reloads-loaded-runtime ()
  "Downloading over a loaded runtime reloads in-process via dyn-loader."
  (let ((system-type 'windows-nt)
        (module-file-suffix ".dll")
        (ghostel-module-dir "C:/ghostel/")
        (downloaded nil)
        (checked-dir nil)
        (messages nil)
        (reloaded nil))
    (let ((comp-enable-subr-trampolines nil)
          (native-comp-enable-subr-trampolines nil)
          (original-featurep (symbol-function 'featurep)))
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (_) nil))
                ((symbol-function 'ghostel--download-module)
                 (lambda (_dir &optional _version _latest-release)
                   (setq downloaded t)
                   t))
                ((symbol-function 'ghostel--native-runtime-ready-p)
                 (lambda () t))
                ((symbol-function 'featurep)
                 (lambda (feature)
                   (or (eq feature 'dyn-loader-module)
                       (funcall original-featurep feature))))
                ((symbol-function 'ghostel--loader-loaded-modules)
                 (lambda () '("ghostel" "conpty-module")))
                ((symbol-function 'dyn-loader-reload)
                 (lambda (module-id)
                   (push module-id reloaded)))
                ((symbol-function 'ghostel--check-module-version)
                 (lambda (dir)
                   (setq checked-dir dir)))
                ((symbol-function 'message)
                 (lambda (format-string &rest args)
                   (push (apply #'format format-string args) messages))))
        (ghostel-download-module)
        (should downloaded)
        (should (equal '("ghostel" "conpty-module")
                       (reverse reloaded)))
        (should (equal (downcase (expand-file-name "C:/ghostel/"))
                       (downcase checked-dir)))
        (should-not (cl-some (lambda (msg)
                               (string-match-p "Restart Emacs" msg))
                             messages))
        (should (member "ghostel: module loaded successfully" messages))))))

(ert-deftest ghostel-test-download-module-rejects-non-loader-runtime ()
  "Downloading over a direct-loaded runtime does not try dyn-loader reload."
  (let ((system-type 'windows-nt)
        (module-file-suffix ".dll")
        (ghostel-module-dir "C:/ghostel/")
        (downloaded nil)
        (checked nil)
        (reloaded nil)
        (original-featurep (symbol-function 'featurep)))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (_) nil))
                ((symbol-function 'ghostel--download-module)
                 (lambda (_dir &optional _version _latest-release)
                   (setq downloaded t)
                   t))
                ((symbol-function 'ghostel--native-runtime-ready-p)
                 (lambda () t))
                ((symbol-function 'featurep)
                 (lambda (feature)
                   (and (not (eq feature 'dyn-loader-module))
                        (funcall original-featurep feature))))
                ((symbol-function 'ghostel--loader-reload)
                 (lambda (&rest _)
                   (setq reloaded t)))
                ((symbol-function 'ghostel--check-module-version)
                 (lambda (&rest _)
                   (setq checked t)))
                ((symbol-function 'message)
                 (lambda (&rest _) nil)))
        (should-error (ghostel-download-module)
                      :type 'user-error)
        (should downloaded)
        (should-not reloaded)
        (should-not checked)))))

(ert-deftest ghostel-test-download-module-rejects-unregistered-loader-runtime ()
  "Downloading over a runtime not registered with dyn-loader does not reload."
  (let ((system-type 'windows-nt)
        (module-file-suffix ".dll")
        (ghostel-module-dir "C:/ghostel/")
        (downloaded nil)
        (checked nil)
        (reloaded nil)
        (original-featurep (symbol-function 'featurep)))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (_) nil))
                ((symbol-function 'ghostel--download-module)
                 (lambda (_dir &optional _version _latest-release)
                   (setq downloaded t)
                   t))
                ((symbol-function 'ghostel--native-runtime-ready-p)
                 (lambda () t))
                ((symbol-function 'featurep)
                 (lambda (feature)
                   (or (eq feature 'dyn-loader-module)
                       (funcall original-featurep feature))))
                ((symbol-function 'ghostel--loader-loaded-modules)
                 (lambda () '("other-module")))
                ((symbol-function 'dyn-loader-reload)
                 (lambda (&rest _)
                   (setq reloaded t)))
                ((symbol-function 'ghostel--check-module-version)
                 (lambda (&rest _)
                   (setq checked t)))
                ((symbol-function 'message)
                 (lambda (&rest _) nil)))
        (should-error (ghostel-download-module)
                      :type 'user-error)
        (should downloaded)
        (should-not reloaded)
        (should-not checked)))))

(ert-deftest ghostel-test-download-module-closes-live-buffers-before-reload ()
  "Downloading over a loader runtime closes live terminals before reload."
  (let ((system-type 'windows-nt)
        (module-file-suffix ".dll")
        (ghostel-module-dir "C:/ghostel/")
        (downloaded nil)
        (checked nil)
        (closed nil)
        (reloaded nil)
        (original-featurep (symbol-function 'featurep)))
    (ghostel-test--without-subr-trampolines
      (cl-letf (((symbol-function 'file-exists-p)
                 (lambda (_) nil))
                ((symbol-function 'ghostel--download-module)
                 (lambda (_dir &optional _version _latest-release)
                   (setq downloaded t)
                   t))
                ((symbol-function 'ghostel--native-runtime-ready-p)
                 (lambda () t))
                ((symbol-function 'featurep)
                 (lambda (feature)
                   (or (eq feature 'dyn-loader-module)
                       (funcall original-featurep feature))))
                ((symbol-function 'ghostel--loader-loaded-modules)
                 (lambda () '("ghostel" "conpty-module")))
                ((symbol-function 'ghostel--live-buffers)
                 (lambda () (list (current-buffer))))
                ((symbol-function 'ghostel--close-live-buffers)
                 (lambda (buffers)
                   (setq closed buffers)))
                ((symbol-function 'dyn-loader-reload)
                 (lambda (&rest _)
                   (setq reloaded t)))
                ((symbol-function 'ghostel--check-module-version)
                 (lambda (&rest _)
                   (setq checked t)))
                ((symbol-function 'message)
                 (lambda (&rest _) nil)))
        (ghostel-download-module)
        (should downloaded)
        (should (equal (list (current-buffer)) closed))
        (should reloaded)
        (should checked)))))

(ert-deftest ghostel-test-module-compile-command-uses-package-dir ()
  "Interactive compilation runs from the Ghostel package directory."
  (let ((source-dir (ghostel-test--fixture-dir "ghostel-build"))
        (compile-command nil)
        (compile-directory nil))
    (let ((comp-enable-subr-trampolines nil)
          (native-comp-enable-subr-trampolines nil))
      (cl-letf (((symbol-function 'locate-library)
                 (lambda (_) (ghostel-test--fixture-path source-dir "ghostel.el")))
                ((symbol-function 'compile)
                 (lambda (command &optional comint)
                   (setq compile-command (list command comint))
                   (setq compile-directory default-directory)
                   t)))
        (ghostel-module-compile)
        (should (equal '("zig build -Doptimize=ReleaseFast -Dcpu=baseline" t) compile-command))
        (should (equal (downcase source-dir)
                       (downcase compile-directory)))))))

(provide 'ghostel-module-test)
;;; ghostel-module-test.el ends here
