# melpazoid <https://github.com/riscy/melpazoid> build checks.

name: melpazoid

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Install
        run: |
          sudo apt-get install emacs && emacs --version
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
      - name: Run
        env:
          LOCAL_REPO: ${{ github.workspace }}
          RECIPE: (ghostel :fetcher github :repo "dakra/ghostel")
          EXIST_OK: false
          WARN_IS_ERROR: true
        run: make -C ~/melpazoid
